url: 'http://localhost:8082'

mongodb:
  server:   ds035260.mongolab.com:35260
  database: heroku_app29472480
  user:     heroku_app29472480
  password: nlh1rlk2dtne6djppuaha44qi9
  connectionString:       # alternative to setting server, database, user and password separately

monitor:
  name:                   origin
  apiUrl:                 'http://wwwatchdog.herokuapp.com/api' # must be accessible without a proxy
  pollingInterval:        10000      # ten seconds
  timeout:                5000       # five seconds
  userAgent:              NodeUptime/3.0 (https://github.com/fzaninotto/uptime)

analyzer:
  updateInterval:         60000      # one minute
  qosAggregationInterval: 600000     # ten minutes
  pingHistory:            8035200000 # three months

autoStartMonitor: true

server:
  port: 80

plugins:
  - ./plugins/console
  - ./plugins/patternMatcher
  - ./plugins/httpOptions
  - ./plugins/email
  - ./plugins/basicAuth

email:
  method:      SMTP  # possible methods are SMTP, SES, or Sendmail
  transport:         # see https://github.com/andris9/nodemailer for transport options
    service:   Gmail # see https://github.com/andris9/Nodemailer/blob/master/lib/wellknown.js for well-known services
    auth:            
      user:    wwwatchdogZEN@gmail.com       # The email account username, e.g. 'username@gmail.com'
      pass:    wwwatchdogZEN!      # The email account password, e.G. 'password'
  event:
    up:        true
    down:      true
    paused:    false
    restarted: false
  message:           
    from:       watchdog@zeneffy.fr     # The message sender, e.g. 'Fred Foo <foo@blurdybloop.com>'
    to:         julien@zeneffy.fr     # The message recipient, e.g. 'bar@blurdybloop.com, baz@blurdybloop.com'
  # The email plugin also uses the main `url` param for hyperlinks in the sent emails

basicAuth:
  username:    superman
  password:    spiderman
verbose: true # only used in dev

webPageTest:
  server: 'http://www.webpagetest.org'
  key:
  testOptions: 
